=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,description?,surface+,name,water,nb_mine,nb_barrel?,alpha_threshold?,is_open,infinite_background?,(sprite,wind)?,music_playlist?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT alpha_threshold (#PCDATA)>
<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, rotation_speed?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT rotation_speed (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

<!ELEMENT music_playlist (#PCDATA)>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/junglemountain/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>USA</country>
 </author>
 
 <surface name="sky" file="drseuss.jpg" />
 <surface name="map" file="dseuss_fg.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Jungle Mountain</name>
 <water>water</water>
 <nb_mine>0</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="goo_drop.png">
     <grid size="34,49" array="1,1"/>
   </image>
 </sprite>

 <wind>
   <nbr_sprite>20</nbr_sprite>
   <need_flip>0</need_flip>
   <mass>1.0</mass>
   <wind_factor>0.0</wind_factor>
   <air_resist_factor>0.005</air_resist_factor>
   <gravity_factor>0.1</gravity_factor>
   <rebounding>false</rebounding>
   <rebound_factor>0.0</rebound_factor>
 </wind>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/titanik/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>grospoisonaujambon</name>
   <nickname>inkey</nickname>
   <email>Lelitchie[AT]hotmail[DOT]fr</email>
   <country>france</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>titanik</name>
 <water>water</water>
 <nb_mine>5</nb_mine>
 <is_open>1</is_open>
 

</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/crystal/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>C. Schalkwijk</name>
    <nickname>Papa.Coen</nickname>
    <email>Papa.Coen@gmail.com</email>
    <country>The Netherlands</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="crystal.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Crystal</name>
  <water>radioactive</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1200" y="700" />
  <point name="lower_right_pad" x="1200" y="0" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/construction/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT warmux.org</email>
    <country>France</country>
  </author>

  <surface name="sky"     file="sky.jpg" /> 

  <sky_layer>3</sky_layer>
  <surface name="sky_layer_0" file="sky0.png" />
  <surface name="sky_layer_1" file="sky1.png" />
  <surface name="sky_layer_2" file="sky2.png" />

  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Construction</name>
  <water>water</water>
  <nb_mine>4</nb_mine>
  <nb_barrel>2</nb_barrel>
  <is_open>1</is_open>
  <music_playlist>construction</music_playlist>

  <sprite name="wind_particle">
     <image file="raindrop.png">
       <grid size="3,101" array="1,1"/>
     </image>
  </sprite>
 
  <wind>
     <nbr_sprite>20</nbr_sprite>
     <need_flip>0</need_flip>
     <mass>1.0</mass>
     <wind_factor>0.7</wind_factor>
     <air_resist_factor>0.01</air_resist_factor>
     <gravity_factor>0.3</gravity_factor>
     <rebounding>false</rebounding>
     <rebound_factor>0.0</rebound_factor>
     <auto_align_particle>true</auto_align_particle>
  </wind>

</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/minersmayhem/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>America</country>
 </author>
 
 <surface name="sky" file="cavebackground.jpg" />
 <surface name="map" file="cave.png" />
 <surface name="preview" file="cavepreview.jpg" />
 
 <name>Miner's Mayhem</name>
 <water>water</water>
 <nb_mine>0</nb_mine>
 <is_open>0</is_open>
 
 <sprite name="wind_particle">
   <image file="gem.png">
     <grid pos="0,0" size="55,52" array="1,1"/>
   </image>
 </sprite>

 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="900" y="800" /> 
 <point name="lower_right_pad" x="900" y="0" /> 

 <wind>
   <nbr_sprite>15</nbr_sprite>
   <need_flip>0</need_flip>
   <mass>1.0</mass>
   <wind_factor>0.2</wind_factor>
   <rotation_speed>0.04</rotation_speed>
   <air_resist_factor>0.05</air_resist_factor>
   <gravity_factor>0.05</gravity_factor>
   <rebounding>false</rebounding>
   <rebound_factor>0.0</rebound_factor>

 </wind>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/cheese/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="emmental.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Cheese</name>
  <water>no</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1400" y="1000" />
  <point name="lower_right_pad" x="1400" y="0" />

  <sprite name="wind_particle">
    <image file="minicheese.png">
      <grid size="60,56" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>6</nbr_sprite>
    <need_flip>1</need_flip>

    <mass>5.0</mass>
    <wind_factor>8.5</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.2</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>3.3</rebound_factor>
  </wind>

  <music_playlist>funfair</music_playlist>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/greehills/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>C. Schalkwijk</name>
    <nickname>Papa.Coen</nickname>
    <email>Papa.Coen@gmail.com</email>
    <country>The Netherlands</country>
  </author>

  <surface name="sky" file="greenhills_sky.jpg" />
  <surface name="map" file="greenhills.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Green Hills</name>
  <water>water</water>
  <nb_mine>3</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1200" y="0" />
  <point name="lower_right_pad" x="1200" y="0" />

  <sprite name="wind_particle">
    <image file="star.png">
      <grid size="125,127" array="1,1"/>
    </image>
  </sprite>

   <wind>
    <nbr_sprite>5</nbr_sprite>
    <need_flip>0</need_flip>
	
    <mass>1.0</mass>
    <wind_factor>7.5</wind_factor>
    <air_resist_factor>0.5</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>1.0</rebound_factor>
  </wind>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/oktopus/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰</name>
    <nickname>yeKcim</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Oktopus</name>
  <water>water</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>

  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="500" y="500" />
  <point name="lower_right_pad" x="500" y="0" />

  <sprite name="wind_particle">
    <image file="bulle.png">
      <grid size="50,50" array="1,1"/>
    </image>
  </sprite>
  <wind>
    <nbr_sprite>60</nbr_sprite>
    <mass>1</mass>
    <wind_factor>5</wind_factor>
    <air_resist_factor>0.5</air_resist_factor>
    <gravity_factor>-1</gravity_factor>
  </wind>

  <music_playlist>sea</music_playlist>

</resources>
