=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,description?,surface+,name,water,nb_mine,nb_barrel?,alpha_threshold?,is_open,infinite_background?,(sprite,wind)?,music_playlist?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT alpha_threshold (#PCDATA)>
<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, rotation_speed?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT rotation_speed (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

<!ELEMENT music_playlist (#PCDATA)>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/qubos/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>America</country>
 </author>
 
 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="500" y="500" /> 
 <point name="lower_right_pad" x="500" y="0" /> 
 
 <surface name="sky" file="bg.jpg" />
 <surface name="map" file="fg.png" />
 <surface name="preview" file="pr.jpg" />
 
 <name>Qubos Castle</name>
  <water>water</water>
 <nb_mine>6</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="qubos_anim.png">
     <grid pos="0,0" size="120,120" array="24,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>5</nbr_sprite>
   <need_flip>0</need_flip>
   <rotation_speed>0</rotation_speed>
   <mass>2.0</mass>
   <wind_factor>6.5</wind_factor>
   <air_resist_factor>0.1</air_resist_factor>
   <gravity_factor>0.1</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>3.3</rebound_factor>
 </wind>
 
 <music_playlist>funfair</music_playlist>
 
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/apocalypse/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>SEBASTIEN MATHIER</name>
   <nickname>SEBASTIEN</nickname>
   <email>mathier AT hotmail.com</email>
   <country>Suisse</country>
 </author>
 
 <surface name="sky" file="apocalypse.jpg" />
 <surface name="map" file="apocalypse.png" />
 <surface name="preview" file="mini.jpg" />
 
 <name>Apocalypse</name>
 <water>lava</water>
 <nb_mine>12</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="vent.png">
     <grid size="97,233" array="1,1"/>
   </image>
 </sprite>

 <add_pad>1</add_pad> 
 <point name="upper_left_pad" x="900" y="800" /> 
 <point name="lower_right_pad" x="900" y="0" /> 

 <wind>
   <nbr_sprite>10</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>3.0</mass>
   <wind_factor>0.1</wind_factor>
   <air_resist_factor>0.3</air_resist_factor>
   <gravity_factor>3</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>1.5</rebound_factor>
 </wind>

 <music_playlist>diabolicux</music_playlist>

</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/dontpushme/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Mathieu Ignacio</name>
    <nickname>matou</nickname>
    <email>mignacio AT april.org</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.png" />
  <surface name="map" file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Don't push me !</name>
  <water>water</water>
  <nb_mine>0</nb_mine>
  <is_open>1</is_open>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/puyoland/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <nickname>psik0</nickname>
    <email>dbernalm AT gmail.com</email>
    <country>Spain</country>
  </author>

  <surface name="sky" file="bg.jpg" />
  <surface name="map" file="puyolandia.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Puyoland</name>
  <water>water</water>
  <nb_mine>10</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1100" y="700" />
  <point name="lower_right_pad" x="1100" y="0" />

  <music_playlist>sea</music_playlist>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/urbanheights/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Christopher L. Stanley</name>
   <nickname>NinjaNumberNine</nickname>
   <email>niftyninjanumbernine@gmail.com</email>
   <country>USA</country>
 </author>

 <surface name="sky" file="radar_bg.jpg" />
 <surface name="map" file="radar_fg.png" />
 <surface name="preview" file="radar_pr.jpg" />
 
 <name>Urban Heights</name>
  <water>water</water>
 <nb_mine>6</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="earthstrip.png">
     <grid size="100,70" array="23,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>5</nbr_sprite>
   <need_flip>0</need_flip>
   <rotation_speed>0.00</rotation_speed>
   <mass>2.0</mass>
   <wind_factor>6.5</wind_factor>
   <air_resist_factor>0.1</air_resist_factor>
   <gravity_factor>0.1</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>3.3</rebound_factor>
 </wind>
 
 <music_playlist>construction</music_playlist>
 
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/icebergs/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Jérémie LEDENTU</name>
    <nickname>JLedN</nickname>
    <email>jledentu AT gmail.com</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Icebergs</name>
  <water>water</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1200" y="400" />
  <point name="lower_right_pad" x="1200" y="0" />

  <sprite name="wind_particle">
    <image file="wp.png">
      <grid size="19,18" array="1,1"/>
    </image>
  </sprite>
 
  <wind>
    <nbr_sprite>15</nbr_sprite>
    <need_flip>1</need_flip>
    <mass>2.0</mass>
    <wind_factor>4.0</wind_factor>
    <air_resist_factor>0.4</air_resist_factor>
    <gravity_factor>0.5</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>1.5</rebound_factor>
  </wind>
  
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/montagnes/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Jeoire de Chassey</name>
   <nickname>Akela NDE</nickname>
   <email>jeoire[a]chassey.net</email>
   <country>France</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="map.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Montagnes</name>
 <water>water</water>
 <nb_mine>5</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="flocon.png">
     <grid size="20,18" array="1,1"/>
   </image>
 </sprite>
 
 <wind>
   <nbr_sprite>6</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>1.0</mass>
   <wind_factor>8.5</wind_factor>
   <air_resist_factor>0.1</air_resist_factor>
   <gravity_factor>0.2</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>2.1</rebound_factor>
 </wind>
 
 <!--<music_playlist>NAMEOFMUSICFILE</music_playlist>-->
 
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/factory/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>kiriep</name>
		<nickname>kiriep</nickname>
		<email>kiriep@gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="sky.jpg" />
	<surface name="map" file="background.png" />
	<surface name="preview" file="preview.jpg" />


	<name>Factory</name>
	<water>no</water>
	<nb_barrel>10</nb_barrel>
	<nb_mine>5</nb_mine>
	<is_open>0</is_open>

  <sprite name="wind_particle">
    <image file="etincelle.png">
      <grid pos="0,0" size="5,5" array="1,1"/>
    </image>
  </sprite>
 
  <wind>
    <nbr_sprite>500</nbr_sprite>
    <need_flip>1</need_flip>
    <mass>0.1</mass>
    <wind_factor>8.0</wind_factor>
    <air_resist_factor>0.1</air_resist_factor>
    <gravity_factor>0.5</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>1.5</rebound_factor>
  </wind>
</resources>
