=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/map.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (author,description?,surface+,name,water,nb_mine,nb_barrel?,alpha_threshold?,is_open,infinite_background?,(sprite,wind)?,music_playlist?) >
<!ELEMENT section (author+)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT author (name,nickname?,email,country)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT country (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT water (#PCDATA)>
<!ELEMENT nb_mine (#PCDATA)>
<!ELEMENT nb_barrel (#PCDATA)>
<!ELEMENT is_open (#PCDATA)>
<!ELEMENT infinite_background (#PCDATA)>

<!ELEMENT alpha_threshold (#PCDATA)>
<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED >

<!ELEMENT wind (nbr_sprite, need_flip?, rotation_speed?, mass, wind_factor, air_resist_factor, gravity_factor, rebounding, rebound_factor)>
<!ELEMENT nbr_sprite (#PCDATA)>
<!ELEMENT need_flip (#PCDATA)>
<!ELEMENT rotation_speed (#PCDATA)>
<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

<!ELEMENT music_playlist (#PCDATA)>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/vulcano/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Olivier Boyer</name>
		<nickname>ziolive</nickname>
		<email>ziolive AT gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="sky2.jpg" />
	<surface name="map" file="background.png" />
	<surface name="preview" file="preview.jpg" />

	<name>Vulcano</name>
	<water>lava</water>
	<nb_mine>7</nb_mine>
	<is_open>0</is_open>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/qingqong/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Anthony CARRÃ‰ and Olivier Boyer</name>
    <nickname>yeKcim and Zi Olive</nickname>
    <email>yeknan AT yahoo DOT fr</email>
    <country>France</country>
  </author>

  <surface name="sky" file="sky.jpg" />
  <surface name="map" file="qingqong.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Qing-Qong</name>
  <water>no</water>
  <nb_mine>5</nb_mine>
  <is_open>1</is_open>
  <!-- pad is given in pixel count. -->
  <add_pad>1</add_pad>
  <point name="upper_left_pad" x="1200" y="700" />
  <point name="lower_right_pad" x="1200" y="0" />

</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/seaship/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Zelinskiy Ivan</name>
   <nickname>ivze</nickname>
   <email>ivze AT bk DOT ru</email>
   <country>Russia</country>
 </author>
 
 <surface name="sky" file="sky.jpg" />
 <surface name="map" file="ship.png" />
 <surface name="preview" file="preview.jpg" />
 
 <name>Sea Ship</name>
 <water>water</water>
 <nb_mine>8</nb_mine>
 <is_open>1</is_open>


   <sprite name="wind_particle">
    <image file="wp.png">
      <grid pos="0,0" size="141,134" array="1,1"/>
    </image>
  </sprite>
 
  <wind>
    <nbr_sprite>15</nbr_sprite>
    <need_flip>1</need_flip>
    <mass>1.0</mass>
    <wind_factor>4.0</wind_factor>
    <air_resist_factor>0.4</air_resist_factor>
    <gravity_factor>0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>1.5</rebound_factor>
  </wind>
  
 
 
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/paint/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
  <author>
    <name>Lawrence AZZOUG</name>
    <nickname>Lami</nickname>
    <email>lami AT warmux.org</email>
    <country>France</country>
  </author>

  <surface name="sky"     file="sky.png" />
  <surface name="map"     file="map.png" />
  <surface name="preview" file="preview.jpg" />

  <name>Paint</name>
  <water>water</water>
  <nb_mine>4</nb_mine>
  <nb_barrel>2</nb_barrel>
  <is_open>1</is_open>

</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/cointv/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
 
 <author>
   <name>Julien Thebaud</name>
   <nickname>Noee</nickname>
   <email>thebaud_julien AT yahoo DOT fr</email>
   <country>France</country>
 </author>
 
 <surface name="sky" file="cointv_fond.jpg" />
 <surface name="map" file="cointv.png" />
 <surface name="preview" file="cointv_preview.jpg" />
 
 <name>Coin Télé</name>
 <water>no</water>
 <nb_mine>5</nb_mine>
 <is_open>1</is_open>
 
 <sprite name="wind_particle">
   <image file="poussiere.png">
     <grid pos="0,0" size="80,80" array="1,1"/>
   </image>
 </sprite>

 
 <wind>
   <nbr_sprite>6</nbr_sprite>
   <need_flip>1</need_flip>
   <mass>5.0</mass>
   <wind_factor>8.5</wind_factor>
   <air_resist_factor>0.2</air_resist_factor>
   <gravity_factor>0.2</gravity_factor>
   <rebounding>true</rebounding>
   <rebound_factor>3.3</rebound_factor>
 </wind>
 
 
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/glass_pyramids/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>jacob</name>
		<nickname>meatlover</nickname>
		<email>jb.meatlover@gmail.com</email>
		<country>USA</country>
	</author>

	<surface name="sky" file="bg.jpg" />
	<surface name="map" file="map.png" />
	<surface name="preview" file="prev.jpg" />


	<name>Glass Pyramids</name>
	<water>water</water>
	<nb_mine>3</nb_mine>
	<nb_barrel>2</nb_barrel>
	<is_open>1</is_open>

	<music_playlist>sea</music_playlist>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/map/paradis/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>Olivier Boyer</name>
		<nickname>ziolive</nickname>
		<email>ziolive AT gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="decor_paradis_bg.jpg" />
	<surface name="map" file="decor_paradis.png" />
	<surface name="preview" file="paradis_preview.jpg" />


	<name>Paradis</name>
	<water>no</water>
	<nb_mine>7</nb_mine>
	<is_open>1</is_open>
	<!-- pad is given in pixel count. -->
	<add_pad>1</add_pad>
	<point name="upper_left_pad" x="0" y="2000" />
	<point name="lower_right_pad" x="0" y="1000" />

	<music_playlist>sea</music_playlist>
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/local/map/futura/config.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../map.dtd" []>
<resources>
	<author>
		<name>kiriep</name>
		<nickname>kiriep</nickname>
		<email>kiriep@gmail.com</email>
		<country>France</country>
	</author>

	<surface name="sky" file="sky.jpg" />
	<surface name="map" file="background.png" />
	<surface name="preview" file="preview.jpg" />


	<name>Futura</name>
	<water>water</water>
	<nb_barrel>5</nb_barrel>
	<nb_mine>10</nb_mine>
	<is_open>1</is_open>

	
</resources>
