=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/weapons.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (surface|sprite|position|hole|color)+>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #REQUIRED file CDATA #REQUIRED>

<!ELEMENT sprite (image, animation?)>
<!ATTLIST sprite name CDATA #REQUIRED>
<!ELEMENT image (grid?)>
<!ATTLIST image file CDATA #REQUIRED>
<!ELEMENT grid EMPTY>
<!ATTLIST grid pos CDATA #REQUIRED size CDATA #REQUIRED array CDATA #REQUIRED>
<!ELEMENT animation EMPTY>
<!ATTLIST animation speed CDATA #IMPLIED loop_mode CDATA #IMPLIED>

<!ELEMENT position EMPTY>
<!ATTLIST position name CDATA #REQUIRED origin CDATA #REQUIRED x CDATA #REQUIRED y CDATA #REQUIRED>

<!ELEMENT hole EMPTY>
<!ATTLIST hole name CDATA #REQUIRED dx CDATA #REQUIRED dy CDATA #REQUIRED>

<!ELEMENT color EMPTY>
<!ATTLIST color name CDATA #REQUIRED r CDATA #REQUIRED g CDATA #REQUIRED b CDATA #REQUIRED a CDATA #REQUIRED>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/weapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resources SYSTEM "weapons.dtd" []>
<resources>

<!-- Common ressources (explosion and impact) -->

  <sprite name="smoke">
    <image file="object/smoke2.png" />
  </sprite>

  <sprite name="smoke_explosion">
    <image file="object/smoke3.png">
      <grid pos="0,0" size="150,150" array="4,1"/>
    </image>
    <animation speed="50"/>
  </sprite>

    <sprite name="smoke_big_explosion">
    <image file="object/kaboom.png">
      <grid pos="0,0" size="100,100" array="9,1"/>
    </image>
    <animation speed="100"/>
  </sprite>

  <sprite name="explosion_particle">
    <image file="object/kaboomk.png">
      <grid pos="0,0" size="100,100" array="4,1"/>
    </image>
    <animation speed="100"/>
  </sprite>

  <sprite name="ill_bubble">
    <image file="object/ill_bubble.png" />
  </sprite>

  <sprite name="fire_particle">
    <image file="object/fire.png" >
      <grid pos="0,0" size="18,35" array="5,1" />
    </image>
  </sprite>

  <sprite name="star_particle">
    <image file="object/star.png" />
  </sprite>

  <sprite name="dark_smoke">
    <image file="object/dark_smoke.png" />
  </sprite>

  <sprite name="yellow_star_particle">
    <image file="object/yellow_star.png" />
  </sprite>

  <sprite name="blue_star_particle">
    <image file="object/blue_star.png" />
  </sprite>

  <sprite name="pink_star_particle">
    <image file="object/pink_star.png" />
  </sprite>

  <sprite name="bullet_particle">
    <image file="weapon/gun/gun_bullet.png" />
  </sprite>

  <sprite name="water_drop">
    <image file="water/water/water_drop.png" />
  </sprite>

  <sprite name="lava_drop">
    <image file="water/lava/lava_drop.png" />
  </sprite>

  <sprite name="radioactive_drop">
    <image file="water/radioactive/radioactive_drop.png" />
  </sprite>

  <sprite name="dirtywater_drop">
    <image file="water/dirtywater/dirtywater_drop.png" />
  </sprite>

  <sprite name="chocolate_drop">
    <image file="water/chocolate/chocolate_drop.png" />
  </sprite>

  <!-- Air attack ressources -->

  <surface name="air_attack_ico" file="weapon/air_attack/air_attack_ico.png" />
  <surface name="air_attack" file="weapon/air_attack/air_attack.png" />
  <position name="air_attack" origin="over" x="0" y="-5" />
  <sprite name="air_attack_plane">
    <image file="weapon/air_attack/air_attack_plane.png">
      <grid pos="0,0" size="200,65" array="3,1"/>
    </image>
    <animation speed="10"/>
  </sprite>
  <sprite name="air_attack_projectile">
    <image file="weapon/air_attack/obus.png" />
  </sprite>

<!-- Air Hammer ressources -->

  <surface name="airhammer_ico" file="weapon/airhammer/airhammer_ico.png" />
  <surface name="airhammer" file="weapon/airhammer/airhammer.png" />
  <position name="airhammer" origin="hand" x="0" y="0" />
  <surface name="airhammer_impact" file="weapon/airhammer/airhammer_impact.png" />

<!-- Automatic-Bazooka ressources -->

  <surface name="automatic_bazooka_ico" file="weapon/bazooka/bazooka_auto_ico.png" />
  <surface name="automatic_bazooka" file="weapon/bazooka/yellow_bazooka.png" />
  <position name="automatic_bazooka" origin="hand" x="25" y="28" />
  <hole name="automatic_bazooka" dx="20" dy="-10" />

<!-- Baseball ressources -->

  <surface name="baseball_ico" file="weapon/baseball/baseball_ico.png" />
  <surface name="baseball_fire" file="weapon/baseball/baseball_hit.png" />
  <surface name="baseball" file="weapon/baseball/baseball.png" />
  <position name="baseball" origin="hand" x="0" y="3" />

<!-- Bazooka ressources -->

  <surface name="bazooka_ico" file="weapon/bazooka/bazooka_ico.png" />
  <surface name="bazooka" file="weapon/bazooka/brown_bazooka.png" />
  <position name="bazooka" origin="hand" x="25" y="28" />
  <hole name="bazooka" dx="20" dy="-10" />
  <surface name="baz_cible" file="weapon/bazooka/baz_cible.png" />
  <sprite name="rocket">
    <image file="weapon/bazooka/missile.png" />
  </sprite>

<!-- Riot bomb ressources -->

  <surface name="riot_bomb_ico" file="weapon/riot_bomb/riot_ico.png" />
  <surface name="riot_bomb" file="weapon/bazooka/green_bazooka.png" />
  <position name="riot_bomb" origin="hand" x="25" y="28" />
  <hole name="riot_bomb" dx="20" dy="-10" />
  <surface name="riot_cible" file="weapon/bazooka/baz_cible.png" />
  <sprite name="riot_rocket">
    <image file="weapon/riot_bomb/missile.png" />
  </sprite>

  <!-- Anvil ressources -->

  <surface name="anvil_launcher" file="weapon/anvil/anvil_launcher.png" />
  <position name="anvil_launcher" origin="hand" x="0" y="5" />
  <surface name="anvil_launcher_ico" file="weapon/anvil/anvil_ico.png" />
  <surface name="anvil" file="weapon/anvil/anvil.png" />
  <sprite name="anvil">
    <image file="weapon/anvil/anvil.png" />
  </sprite>

<!-- Bounce ball ressources -->

  <surface name="bounce_ball_ico" file="weapon/bounce_ball/bounce_ball_ico.png" />
  <surface name="bounce_ball" file="weapon/bounce_ball/bounce_ball.png" />
  <sprite name="bounce_ball">
    <image file="weapon/bounce_ball/bounce_ball.png" />
  </sprite>
  <position name="bounce_ball" origin="hand" x="7" y="9" />

<!-- Clusterbomb ressources -->

  <surface name="cluster_bomb_ico" file="weapon/cluster_bomb/clusterbomb_ico.png" />
  <surface name="cluster_bomb" file="weapon/cluster_bomb/clusterbomb.png" />
  <position name="cluster_bomb" origin="hand" x="6" y="9" />
  <sprite name="cluster_bomb">
    <image file="weapon/cluster_bomb/clusterbomb.png" />
  </sprite>
  <sprite name="cluster">
    <image file="weapon/cluster_bomb/cluster.png" />
  </sprite>

<!-- Construct resources -->

  <surface name="construct_ico" file="weapon/construct/construct_icon.png" />
  <surface name="construct" file="weapon/construct/construct_icon_mini.png" />
  <position name="construct" origin="over" x="6" y="9" />
  <sprite name="construct_spr">
    <image file="weapon/construct/construct_spr.png" />
  </sprite>

<!-- Dynamite ressources -->

  <surface name="dynamite_ico" file="weapon/dynamite/dynamite_ico.png" />
  <surface name="dynamite" file="weapon/dynamite/dynamite.png" />
  <position name="dynamite" origin="hand" x="5" y="6" />
  <sprite name="dynamite_bullet">
    <image file="weapon/dynamite/dynamite_ani.png">
      <grid pos="0,0" size="14,15" array="11,1" />
    </image>
  </sprite>
  <sprite name="dynamite_anim">
    <image file="weapon/dynamite/dynamite_ani.png">
      <grid pos="0,0" size="14,15" array="11,1" />
    </image>
  </sprite>

<!-- Flamethrower ressources -->
  <surface name="flamethrower_ico" file="weapon/flamethrower/flame_ico.png" />
  <surface name="flamethrower_fire" file="weapon/gun/gun_fire.png" />
  <sprite name="flamethrower_bullet">
    <image file="weapon/flamethrower/flame_bullet.png" />
  </sprite>
  <surface name="flamethrower" file="weapon/flamethrower/flame.png" />
  <position name="flamethrower" origin="hand" x="4" y="10" />
  <hole name="flamethrower" dx="31" dy="-10" />

<!-- Grenade ressources -->

  <surface name="grenade_ico" file="weapon/grenade/grenade_ico.png" />
  <surface name="grenade" file="weapon/grenade/grenade.png" />
  <position name="grenade" origin="hand" x="7" y="9" />
  <sprite name="grenade">
    <image file="weapon/grenade/grenade.png" />
  </sprite>

<!-- Gun ressources -->

  <surface name="gun_ico" file="weapon/gun/gun_ico.png" />
  <surface name="gun" file="weapon/gun/gun.png" />
  <position name="gun" origin="hand" x="5" y="10" />
  <hole name="gun" dx="18" dy="-6" />
  <surface name="gun_fire" file="weapon/gun/gun_fire.png" />
  <sprite name="gun_bullet">
    <image file="weapon/gun/gun_bullet.png" />
  </sprite>

<!-- Shotgun ressources -->

  <surface name="shotgun_ico" file="weapon/shotgun/shotgun_ico.png" />
  <surface name="shotgun_fire" file="weapon/gun/gun_fire.png" />
  <sprite name="buckshot">
    <image file="weapon/shotgun/buckshot.png" />
  </sprite>
  <surface name="shotgun" file="weapon/shotgun/shotgun.png" />
  <position name="shotgun" origin="hand" x="12" y="4" />
  <hole name="shotgun" dx="32" dy="-3" />

<!-- Holly Grenade ressources -->

  <surface name="disco_grenade_ico" file="weapon/disco_grenade/disco_grenade_ico.png" />
  <surface name="disco_grenade" file="weapon/disco_grenade/disco_grenade.png" />
  <position name="disco_grenade" origin="hand" x="10" y="6" />
  <sprite name="disco_grenade">
    <image file="weapon/disco_grenade/disco_grenade.png" />
  </sprite>

  <!-- Gnu ressources -->

  <surface name="gnulauncher_ico" file="weapon/gnu/gnu_ico.png" />
  <surface name="gnulauncher" file="weapon/gnu/gnulauncher.png" />
  <position name="gnulauncher" origin="hand" x="20" y="20" />
  <sprite name="gnu">
    <image file="weapon/gnu/gnu.png">
      <grid pos="0,0" size="47,38" array="4,1" />
    </image>
    <animation speed="35" loop_mode="pingpong" />
  </sprite>

  <!-- Polecat ressources -->

  <surface name="polecatlauncher_ico" file="weapon/polecat/polecat_ico.png" />
  <surface name="polecatlauncher" file="weapon/polecat/polecatlauncher.png" />
  <position name="polecatlauncher" origin="hand" x="26" y="18" />
  <sprite name="polecat_fart">
    <image file="weapon/polecat/polecat_fart.png" />
  </sprite>
  <sprite name="polecat">
    <image file="weapon/polecat/polecat.png">
      <grid pos="0,0" size="52,25" array="1,1" />
    </image>
    <animation speed="35" loop_mode="pingpong" />
  </sprite>

<!-- JetPack ressources -->

  <position name="jetpack" origin="hand" x="5" y="6" />
  <surface name="jetpack_ico" file="weapon/jet_pack/jet_pack_ico.png" />

<!-- LowGrav ressources -->

  <surface name="lowgrav_ico" file="weapon/lowgrav/lowgrav_ico.png" />
  <position name="lowgrav" origin="hand" x="24" y="23" />

<!-- Mine ressources -->

  <surface name="minelauncher_ico" file="weapon/mine/mine_ico.png" />
  <surface name="minelauncher" file="weapon/mine/mine.png" />
  <position name="minelauncher" origin="hand" x="9" y="19" />
  <sprite name="mine">
    <image file="weapon/mine/mine_anim.png">
