=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/sound/profile.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT profile (sound+)>
<!ELEMENT sound EMPTY>
<!ATTLIST sound sample CDATA #REQUIRED file CDATA #REQUIRED>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/sound/default/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profile SYSTEM "../profile.dtd">
<profile>

  <!-- VOICES -->

  <sound sample="jump"                           file="voices/jump.ogg" />
  <sound sample="superjump"                      file="voices/superjump.ogg" />
  <sound sample="back_jump"                      file="voices/backjump.ogg" />
  
  <sound sample="death"                          file="voices/death1.ogg" />
  <sound sample="death"                          file="voices/death2.ogg" />
  <sound sample="death"                          file="voices/death3.ogg" />
  <sound sample="death"                          file="voices/death4.ogg" />
  <sound sample="death"                          file="voices/death5.ogg" />
  
  <sound sample="suicide"                        file="voices/suicide.ogg" />
  
  <sound sample="injured_light"                  file="voices/injured_light1.ogg" />
  <sound sample="injured_light"                  file="voices/injured_light2.ogg" />
  <sound sample="injured_light"                  file="voices/injured_light3.ogg" />
  <sound sample="injured_light"                  file="voices/injured_light4.ogg" />
  <sound sample="injured_light"                  file="voices/injured_light5.ogg" />
  <sound sample="injured_medium"                 file="voices/injured_medium1.ogg" />
  <sound sample="injured_medium"                 file="voices/injured_medium2.ogg" />
  <sound sample="injured_medium"                 file="voices/injured_medium3.ogg" />
  <sound sample="injured_medium"                 file="voices/injured_medium4.ogg" />
  <sound sample="injured_medium"                 file="voices/injured_medium5.ogg" />
  <sound sample="injured_high"                   file="voices/injured_high1.ogg" />
  <sound sample="injured_high"                   file="voices/injured_high2.ogg" />
  <sound sample="injured_high"                   file="voices/injured_high3.ogg" />
  <sound sample="injured_high"                   file="voices/injured_high4.ogg" />
  <sound sample="injured_high"                   file="voices/injured_high5.ogg" />

  <sound sample="fire"                           file="voices/fire1.ogg" />
  <sound sample="fire"                           file="voices/fire2.ogg" />
  <sound sample="fire"                           file="voices/fire3.ogg" />
  <sound sample="fire"                           file="voices/fire4.ogg" />
  <sound sample="fire"                           file="voices/fire5.ogg" />
  <sound sample="fire"                           file="voices/fire6.ogg" />
  
  <sound sample="friendly_fire"                  file="voices/friendly_fire1.ogg" />
  <sound sample="friendly_fire"                  file="voices/friendly_fire2.ogg" />
  <sound sample="friendly_fire"                  file="voices/friendly_fire3.ogg" />
  
  <sound sample="happy"                          file="voices/happy1.ogg" />

  <sound sample="out"                            file="voices/out.ogg" />

  <sound sample="leader_change"                  file="voices/theme1.ogg" />
  <sound sample="leader_change"                  file="voices/theme2.ogg" />
  <sound sample="leader_change"                  file="voices/theme3.ogg" />
  <sound sample="leader_change"                  file="voices/theme4.ogg" />
  <sound sample="leader_change"                  file="voices/theme5.ogg" />
  <sound sample="leader_change"                  file="voices/theme6.ogg" />
  <sound sample="leader_change"                  file="voices/theme7.ogg" />
  <sound sample="leader_change"                  file="voices/theme8.ogg" />
  <sound sample="leader_change"                  file="voices/theme9.ogg" />
  
  
  
  <!-- WEAPONS -->
  
  <sound sample="weapon/aircraft_bomb_falling"   file="weapons/aircraft_bomb_falling.ogg" />
  <sound sample="weapon/aircraft_flying"         file="weapons/aircraft_flying.ogg" />
  <sound sample="weapon/airhammer"               file="weapons/airhammer_used.ogg" />
  <sound sample="weapon/airhammer_select"        file="weapons/airhammer_selected.ogg" />
  <sound sample="weapon/anvil_collision"         file="weapons/anvil_collision.ogg" />
  <sound sample="weapon/anvil_fall"              file="weapons/anvil_fall.ogg" />
  <sound sample="weapon/automatic_rocket_flying" file="weapons/auto_rocket_flying.ogg" />
  <sound sample="weapon/baseball"                file="weapons/baseball.ogg" />
  <sound sample="weapon/baseball_homerun"        file="weapons/homerun.ogg" />
  <sound sample="weapon/disco_grenade_bounce"    file="weapons/grenade_bounce.ogg" />
  <sound sample="weapon/disco_grenade_music"     file="weapons/disco_grenade_music.ogg" />
  <sound sample="weapon/dynamite_exp"            file="weapons/dynamite_exp.ogg" />
  <sound sample="weapon/dynamite_fuze"           file="weapons/dynamite_fuze.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion1.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion2.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion3.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion4.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion5.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion6.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion7.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion8.ogg" />
  <sound sample="weapon/explosion"               file="weapons/explosion9.ogg" />
  <sound sample="weapon/flamethrower"            file="weapons/flame.ogg" />
  <sound sample="weapon/gnu_bounce"              file="weapons/gnu_bounce.ogg" />
  <sound sample="weapon/grapple_attaching"       file="weapons/grapple_attaching.ogg" />
  <sound sample="weapon/grapple_cable"           file="weapons/grapple_cable.ogg" />
  <sound sample="weapon/grapple_detaching"       file="weapons/grapple_detaching.ogg" />
  <sound sample="weapon/grenade_bounce"          file="weapons/grenade_bounce.ogg" />
  <sound sample="weapon/footbomb_bounce"         file="weapons/footbomb_bounce.ogg" />
  <sound sample="weapon/gun"                     file="weapons/gun.ogg" />
  <sound sample="weapon/load"                    file="weapons/load.ogg" />
  <sound sample="weapon/m16"                     file="weapons/m16.ogg" />
  <sound sample="weapon/m16_cartridge"           file="weapons/m16_cartridge.ogg" />
  <sound sample="weapon/mine_beep"               file="weapons/mine_beep.ogg" />
  <sound sample="weapon/ricoche1"                file="weapons/ricoche1.ogg" />
  <sound sample="weapon/ricoche2"                file="weapons/ricoche2.ogg" />
  <sound sample="weapon/ricoche3"                file="weapons/ricoche3.ogg" />
  <sound sample="weapon/riot_bomb_exp"           file="weapons/riot_bomb_exp.ogg" />
  <sound sample="weapon/riotbomb_rocket_flying"  file="weapons/riot_flying.ogg" />
  <sound sample="weapon/rocket_flying"           file="weapons/rocket_flying.ogg" />
  <sound sample="weapon/shotgun"                 file="weapons/shotgun.ogg" />
  <sound sample="weapon/suicide"                 file="weapons/suicide.ogg" />
  <sound sample="weapon/slap"                    file="weapons/slap.ogg" />
  <sound sample="weapon/supertux_flying"         file="weapons/supertux_flying.ogg" />
  <sound sample="weapon/supertux_swimming"       file="weapons/supertux_swimming.ogg" />
  <sound sample="weapon/teleport_end"            file="weapons/teleport_land.ogg" />
  <sound sample="weapon/teleport_start"          file="weapons/teleport_start.ogg" />
  <sound sample="weapon/cluzooka_shot"           file="weapons/cluzooka_shot.ogg" />
  <sound sample="weapon/cluzooka_hit"            file="weapons/cluzooka_hit.ogg" />
  <sound sample="weapon/jetpack"                 file="weapons/jetpack.ogg" />
  <sound sample="fire/touch_ground"              file="weapons/embers1.ogg" />
  <sound sample="fire/touch_ground"              file="weapons/embers2.ogg" />
  <sound sample="fire/touch_ground"              file="weapons/embers3.ogg" />
  <sound sample="weapon/construct"               file="weapons/construct.ogg" />
  <sound sample="weapon/lowgrav"                 file="weapons/lowgravity.ogg" />
  <sound sample="weapon/polecat_fart"            file="weapons/polecat.ogg" />
  <sound sample="weapon/blowtorch"               file="weapons/blowtorch.ogg" />
  <sound sample="weapon/syringe_shoot"           file="weapons/syringe.ogg" />  
  
  <!-- MISC  -->
  
  <sound sample="box/falling"                    file="misc/box_falling.ogg" />
  <sound sample="box/hitting_ground"             file="misc/box_hitting_ground.ogg" />
  <sound sample="box/picking_up"                 file="misc/box_picking_up.ogg" />
  <sound sample="box/medkit_picking_up"          file="misc/box_picking_up.ogg" />

  <sound sample="change_weapon"                  file="misc/change_weapon.ogg" />
  <sound sample="character/change_in_same_team"  file="misc/character_change.ogg" />

  <sound sample="start_turn"                     file="misc/start_turn.ogg" />
  <sound sample="countdown-end_turn"             file="misc/countdown-endturn.ogg" />
  <sound sample="end_turn"                       file="misc/end_turn.ogg" />
  <sound sample="skip_turn"                      file="misc/skip_turn.ogg" />
  
  <sound sample="menu/cancel"                    file="misc/cancel.ogg" />
  <sound sample="menu/clic"                      file="misc/clic.ogg" />
  <sound sample="menu/error"                     file="misc/error.ogg" />
  <sound sample="menu/ok"                        file="misc/ok.ogg" />
  <sound sample="menu/weapon_menu_hide"          file="misc/weapon_hide.ogg" />
  <sound sample="menu/weapon_menu_show"          file="misc/weapon_show.ogg" />
  <sound sample="menu/newcomer"                  file="misc/newcomer.ogg" />

  <sound sample="step"                           file="misc/step.ogg" />
