=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/game_mode/objects.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT objects_physics (
          character,bonus_box,medkit,barrel,anvil,
          wind_particle,smoke_particle,polecat_fart_particle,fire_particle,explosion_smoke_particle,
          dark_smoke,star_particle,magic_star_particle,bullet_particle, ground_particle,
          body_member_particle,teleport_member_particle,
          gun_bullet,buckshot,m16_bullet,snipe_rifle_bullet,rocket,riot_rocket,grenade,disco_grenade,
          cluster_bomb,cluster,dynamite_bullet,air_attack_plane,air_attack_projectile,supertux,
          gnu,polecat,bounce_ball,mine
  )>

<!-- To copy-paste and modify if you want to add an object -->
<!-- <!ELEMENT object (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)> -->

<!ELEMENT character (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT bonus_box (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT medkit (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT barrel (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT anvil (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>

<!ELEMENT wind_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT smoke_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT polecat_fart_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT fire_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT explosion_smoke_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT dark_smoke (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT star_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT magic_star_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT bullet_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT ground_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT body_member_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT teleport_member_particle (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>

<!ELEMENT gun_bullet (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT buckshot (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT m16_bullet (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT snipe_rifle_bullet (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT rocket (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT riot_rocket (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT grenade (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT disco_grenade (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT cluster_bomb (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT cluster (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT dynamite_bullet (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT air_attack_plane (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT air_attack_projectile (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT supertux (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT gnu (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT polecat (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT bounce_ball (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>
<!ELEMENT mine (mass,wind_factor, air_resist_factor,gravity_factor,rebounding,rebound_factor)>

<!ELEMENT mass (#PCDATA)>
<!ELEMENT wind_factor (#PCDATA)>
<!ELEMENT air_resist_factor (#PCDATA)>
<!ELEMENT gravity_factor (#PCDATA)>
<!ELEMENT rebounding (#PCDATA)>
<!ELEMENT rebound_factor (#PCDATA)>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/game_mode/default_objects.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE objects_physics SYSTEM "objects.dtd" []>
<objects_physics>

  <!-- Various objects configs -->

  <character>
    <mass>100.0</mass>
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>0.1</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.25</rebound_factor>
  </character>

  <bonus_box>
    <mass>100.0</mass>
    <!-- A wind factor of 0 reduce the chance that bug #15034 occurs. -->
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>16.0</air_resist_factor>
    <gravity_factor>1.2</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </bonus_box>

  <medkit>
    <mass>100.0</mass>
    <!-- A wind factor of 0 reduce the chance that bug #15034 occurs. -->
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>16.0</air_resist_factor>
    <gravity_factor>1.2</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </medkit>

  <barrel>
    <mass>1000.0</mass>
    <wind_factor>0.3</wind_factor>
    <air_resist_factor>20.0</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </barrel>

  <anvil>
    <mass>10000.0</mass>
    <wind_factor>0.3</wind_factor>
    <air_resist_factor>20.0</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </anvil>

  <!-- Dummy value, will be overwritten by the value contained in each
       map config file  -->
  <wind_particle>
    <mass>50.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>1.0</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </wind_particle>

  <!-- Particles Configs -->
  <smoke_particle>  <!-- Unused particle -->
    <mass>0.5</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>-1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </smoke_particle>

  <polecat_fart_particle>  <!-- Polecat Fart -->
    <mass>0.5</mass>
    <wind_factor>1.5</wind_factor>
    <air_resist_factor>0.1</air_resist_factor>
    <gravity_factor>-0.2</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </polecat_fart_particle>

  <fire_particle>  <!-- Particle used during explosions -->
    <mass>100.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </fire_particle>

  <explosion_smoke_particle> <!-- Particle used during explosions -->
    <mass>0.5</mass>
    <wind_factor>10.0</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>  <!-- Randomly set in the code -->
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </explosion_smoke_particle>

  <explosion_particle> <!-- Particle used during explosions -->
    <mass>0.0</mass>
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </explosion_particle>

  <dark_smoke>  <!-- Particle bazooka and auto-bazooka... -->
    <mass>0.5</mass>
    <wind_factor>0.2</wind_factor>
    <air_resist_factor>0.5</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </dark_smoke>

  <star_particle>  <!-- Particle for tux weapon -->
    <mass>0.5</mass>
    <wind_factor>0.2</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </star_particle>

  <magic_star_particle> <!-- Particle for the disco grenade -->
    <mass>0.5</mass>
    <wind_factor>0.2</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </magic_star_particle>

  <bullet_particle> <!-- the gun and M16 -->
    <mass>2.0</mass>
    <wind_factor>0.01</wind_factor>
    <air_resist_factor>0.01</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.7</rebound_factor>
  </bullet_particle>

  <ground_particle> <!-- with airhammer -->
      <mass>100.0</mass>
      <wind_factor>0.01</wind_factor>
      <air_resist_factor>0.01</air_resist_factor>
      <gravity_factor>1.0</gravity_factor>
      <rebounding>false</rebounding>
      <rebound_factor>0.7</rebound_factor>
  </ground_particle>

  <body_member_particle> <!-- during suicide -->
    <mass>100.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>1.0</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.7</rebound_factor>
  </body_member_particle>

  <teleport_member_particle> <!-- during teleportation -->
    <mass>1.0</mass>
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>1.0</air_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.7</rebound_factor>
  </teleport_member_particle>

  <water_particle>  <!-- when falling into water -->
    <mass>2.0</mass>
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>0.2</air_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.0</rebound_factor>
  </water_particle>

  <!-- Weapons Configs -->
  <!-- Weapons bullets -->
  <gun_bullet>
    <mass>2.0</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.10</water_resist_factor>
    <gravity_factor>0.1</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </gun_bullet>

  <buckshot> <!-- shotgun ammo -->
    <mass>1.0</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.0</water_resist_factor>
    <gravity_factor>0.1</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </buckshot>

  <m16_bullet>
    <mass>2.0</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.0</water_resist_factor>
    <gravity_factor>0.1</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </m16_bullet>

  <snipe_rifle_bullet>
    <mass>2.0</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.01</water_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </snipe_rifle_bullet>

  <rail_bullet>
    <mass>0.1</mass>
    <wind_factor>0.0</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.0</water_resist_factor>
    <gravity_factor>0.0</gravity_factor>
    <rebounding>false</rebounding>
  </rail_bullet>

  <flamethrower_bullet>
    <mass>5.0</mass>
    <wind_factor>0.8</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <gravity_factor>0.2</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </flamethrower_bullet>

  <!-- Weapons projectiles -->
  <!-- Bazooka and automatic bazookas rockets -->
  <rocket>
    <mass>20.0</mass>
    <wind_factor>75.0</wind_factor>
    <air_resist_factor>0</air_resist_factor>
    <water_resist_factor>2.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </rocket>

  <cluz_rocket>
    <mass>15.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0</air_resist_factor>
    <water_resist_factor>2.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.9</rebound_factor>
  </cluz_rocket>

  <cluz_cluster>
    <mass>5.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0</air_resist_factor>
    <water_resist_factor>1.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.9</rebound_factor>
  </cluz_cluster>

  <riot_rocket>
    <mass>50.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.8</air_resist_factor>
    <water_resist_factor>5.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>false</rebounding>
    <rebound_factor>0.01</rebound_factor>
  </riot_rocket>

  <grenade>
    <mass>30.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>8.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.7</rebound_factor>
  </grenade>

  <disco_grenade>
    <mass>2.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.0</air_resist_factor>
    <water_resist_factor>0.5</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.4</rebound_factor>
  </disco_grenade>

  <cluster_bomb>
    <mass>30.0</mass>
    <wind_factor>1.0</wind_factor>
    <air_resist_factor>0.3</air_resist_factor>
    <water_resist_factor>4.0</water_resist_factor>
    <gravity_factor>1.0</gravity_factor>
    <rebounding>true</rebounding>
    <rebound_factor>0.7</rebound_factor>
  </cluster_bomb>

  <cluster>
    <mass>30.0</mass>
