=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/team.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (name,surface,team) >

<!ELEMENT name (#PCDATA)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #FIXED "flag" file CDATA #REQUIRED>

<!ELEMENT team (character+)>

<!ELEMENT character EMPTY>
<!ATTLIST character name CDATA #REQUIRED body CDATA #REQUIRED>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/data/team/ooo/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>OOo</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="OOo" body="ooo"/>
    <character name="Writer" body="ooo"/>
    <character name="Calc" body="ooo"/>
    <character name="Impress" body="ooo"/>
    <character name="Base" body="ooo"/>
    <character name="Draw" body="ooo"/>
    <character name="Math" body="ooo"/>
    <character name="Quickstarter" body="ooo"/>
    <character name="OpenDocument" body="ooo"/>
    <character name="OOoConv" body="ooo"/>
    <character name="PortableOOo" body="ooo"/>
    <character name="OOo HG" body="ooo"/>
    <character name="Cart'OOo" body="ooo"/>
    <character name="Hist'OOo" body="ooo"/>
    <character name="GÃ©'OOo" body="ooo"/> 
  </team>
    <color name="teamcolor" r="250" g="250" b="32" a="255" />
</resources>
