=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/team.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (name,surface,team) >

<!ELEMENT name (#PCDATA)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #FIXED "flag" file CDATA #REQUIRED>

<!ELEMENT team (character+)>

<!ELEMENT character EMPTY>
<!ATTLIST character name CDATA #REQUIRED body CDATA #REQUIRED>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/tux/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Tux</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Tux" body="tux" />
    <character name="Chilly Willy" body="tux" />
    <character name="Pingu" body="tux" />
    <character name="Royal" body="tux" />
    <character name="Gorfou" body="tux" />
    <character name="Papou" body="tux" />
    <character name="Empereur" body="tux" />
    <character name="Pygmée" body="tux" />
    <character name="Antipode" body="tux" />
    <character name="Adélie" body="tux" />
    <character name="Pittsburgh" body="tux" />
    <character name="Pengo" body="tux" />
    <character name="Bandit" body="tux" />
    <character name="Lea" body="tux" />   
  </team>
    <color name="teamcolor" r="32" g="32" b="32" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/beastie/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Beastie</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Beastie" body="beastie" />
    <character name="FreeBSD" body="beastie" />
    <character name="DragonFlyBSD" body="beastie" />
    <character name="OpenBSD" body="beastie" />
    <character name="NetBSD" body="beastie" />
    <character name="PC-BSD" body="beastie" />
    <character name="DesktopBSD" body="beastie" />
    <character name="MirBSD" body="beastie" />
    <character name="kFreeBSD" body="beastie" />
    <character name="MidnightBSD" body="beastie" />
    <character name="666" body="beastie" />
  </team>
  <color name="teamcolor" r="128" g="138" b="31" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/php/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>PHP</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="PHP" body="php" />
    <character name="Jumbo" body="php" />
    <character name="Dumbo" body="php" />
    <character name="Babar" body="php" />
    <character name="Joseph Merrick" body="php" />
    <character name="Ganesh" body="php" />
    <character name="Gus Van Sant" body="php" />
    <character name="The White Stripes" body="php" />
    <character name="Loxodonta cyclotis" body="php" />
    <character name="Loxodonta africana" body="php" />
    <character name="Elephas maximus" body="php" />
    <character name="Elephas recki" body="php" />
    <character name="Stegodon" body="php" />
    <character name="Mammuthus" body="php" />
  </team>
    <color name="teamcolor" r="32" g="38" b="59" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/thunderbird/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Thunderbird</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Thunderbird" body="thunderbird" />
    <character name="Gibson" body="thunderbird" />
    <character name="Phorusrhacidae" body="thunderbird" />
    <character name="Dromornithidae" body="thunderbird" />
    <character name="Train" body="thunderbird" />
    <character name="Ford" body="thunderbird" />
    <character name="Triumph" body="thunderbird" />
    <character name="Royal Enfield" body="thunderbird" />    
    <character name="Albuquerque" body="thunderbird" />
    <character name="UBC" body="thunderbird" />
    <character name="Hamilton" body="thunderbird" />
    <character name="Seattle" body="thunderbird" />
    <character name="Squadron" body="thunderbird" />
    <character name="Missile" body="thunderbird" />
  </team>
    <color name="teamcolor" r="15" g="65" b="106" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/spip/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Spip</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
	<character name="ARNO*" body="spip"/>
	<character name="Pit'" body="spip"/>
	<character name="Fil" body="spip"/>
	<character name="ESJ" body="spip"/>
	<character name="Kliké" body="spip"/>
	<character name="Cerdic" body="spip"/>	
	<character name="Têtue" body="spip"/>
	<character name="Renââto" body="spip"/>
	<character name="Piif" body="spip"/>
	<character name="bennybi" body="spip"/>
	<character name="BoOz" body="spip"/>
	<character name="Mortimer" body="spip"/>
	<character name="toggg" body="spip"/>
	<character name="Atchoum" body="spip"/>	
	<character name="Alexandra Maison" body="spip"/>
	<character name="izo" body="spip"/>
  </team>
    <color name="teamcolor" r="146" g="105" b="44" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/data/team/nupik/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Nupik</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="NuFW" body="nupik" />
    <character name="Sonic" body="nupik" />
    <character name="Genus Atelerix" body="nupik" />
    <character name="Genus Erinaceus" body="nupik" />
    <character name="Genus Hemiechinus" body="nupik" />
    <character name="Genus Mesechinus" body="nupik" />
    <character name="Blonde hedgehogs" body="nupik" />
    <character name="WIPFW" body="nupik" />
    <character name="Winsock" body="nupik" />
    <character name="TDI FireWall" body="nupik" />
    <character name="CodeSeeker" body="nupik" />
    <character name="Ipfwadm" body="nupik" />
    <character name="Shorewall" body="nupik" />
    <character name="Zorp" body="nupik" /> 
  </team>
    <color name="teamcolor" r="181" g="64" b="138" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/data/team/godzilla/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Godzilla</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Godzilla" body="godzilla" />
    <character name="Godzilla Jr alias Minilla" body="godzilla" />
    <character name="GINO" body="godzilla" />
    <character name="GINO Jr" body="godzilla" />
    <character name="Mothra" body="godzilla" />
    <character name="Anguirius" body="godzilla" />
    <character name="Gigan" body="godzilla" />
    <character name="King Ghidorah" body="godzilla" />
    <character name="Rodan" body="godzilla" />
    <character name="Baragon" body="godzilla" />
    <character name="Space Godzilla" body="godzilla" />
    <character name="Destoryah" body="godzilla" />
    <character name="Mechagodzilla" body="godzilla" />
    <character name="Jet Jaguar" body="godzilla" /> 
  </team>
    <color name="teamcolor" r="14" g="232" b="232" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/postfix/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Postfix</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
	<character name="Mus crociduroides" body="postfix"/>
	<character name="Mus mayori" body="postfix"/>
	<character name="Mus pahari" body="postfix"/>
	<character name="Mus vulcani" body="postfix"/>
	<character name="Mus booduga" body="postfix"/>
	<character name="Mus caroli" body="postfix"/>	
	<character name="Mus cervicolor" body="postfix"/>
	<character name="Mus cookii" body="postfix"/>
	<character name="Mus cypriacus" body="postfix"/>
	<character name="Mus majorius" body="postfix"/>
	<character name="Mus famulus" body="postfix"/>
	<character name="Mus fragilicauda" body="postfix"/>
	<character name="Mus macedonicus" body="postfix"/>
	<character name="Mus musculus" body="postfix"/>	
	<character name="Mus nitidulus" body="postfix"/>
	<character name="Mus spicilegus" body="postfix"/>
  </team>
    <color name="teamcolor" r="96" g="98" b="95" a="255" />
</resources>
