=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/team.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resources (name,surface,team) >

<!ELEMENT name (#PCDATA)>
<!ATTLIST section title CDATA #REQUIRED>

<!ELEMENT surface EMPTY>
<!ATTLIST surface name CDATA #FIXED "flag" file CDATA #REQUIRED>

<!ELEMENT team (character+)>

<!ELEMENT character EMPTY>
<!ATTLIST character name CDATA #REQUIRED body CDATA #REQUIRED>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/bugzilla/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Bugzilla</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
	<character name="Bugzilla" body="bugzilla"/>
	<character name="Bugtracker" body="bugzilla"/>
	<character name="Zarro Boogs" body="bugzilla"/>
	<character name="Mozilla  project" body="bugzilla"/>
	<character name="Netscape Communications" body="bugzilla"/>
	<character name="Testing tool" body="bugzilla"/>	
	<character name="Arthropods" body="bugzilla"/>
	<character name="True Bugs" body="bugzilla"/>
	<character name="Bugs Meany" body="bugzilla"/>
	<character name="Bug" body="bugzilla"/>
	<character name="Hemiptera" body="bugzilla"/>
	<character name="Hybrid Dog" body="bugzilla"/>
  </team>
    <color name="teamcolor" r="188" g="151" b="103" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/konqi/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Konqi</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Konqui" body="konqi" />
    <character name="Kopete" body="konqi" />
    <character name="KDevelop" body="konqi" />
    <character name="KMail" body="konqi" />
    <character name="Kate" body="konqi" />
    <character name="K3B" body="konqi" />
    <character name="KFormula" body="konqi" />
    <character name="KOffice" body="konqi" />
    <character name="Kontact" body="konqi" />
    <character name="Krita" body="konqi" />
    <character name="digiKam" body="konqi" />
    <character name="Kicker" body="konqi" />
    <character name="okular" body="konqi" />
    <character name="KPDF" body="konqi" />
  </team>
    <color name="teamcolor" r="121" g="164" b="38" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/snort/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Snort</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Snort" body="snort" />
    <character name="SnortSnarf" body="snort" />
    <character name="ACID" body="snort" />
    <character name="Sguil" body="snort" />
    <character name="BASE" body="snort" />
    <character name="Bearded Pig" body="snort" />
    <character name="Vietnamese Warty Pig" body="snort" />
    <character name="Visayas Warty Pig" body="snort" />
    <character name="Celebes Warty Pig" body="snort" />
    <character name="Poulter Warty Pig" body="snort" />
    <character name="Flores Warty Pig" body="snort" />
    <character name="Philippine Warty Pig" body="snort" />
    <character name="Pigmy Hog" body="snort" />
    <character name="Timor Warty Pig" body="snort" />
  </team>
    <color name="teamcolor" r="240" g="90" b="90" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux-data/data/team/predator/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Predator</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
	<character name="Yautja" body="predator"/>
	<character name="Elder" body="predator"/>
	<character name="Wolf" body="predator"/>
	<character name="Bad blood" body="predator"/>
	<character name="Warrior" body="predator"/>
	<character name="Celtic" body="predator"/>	
	<character name="Scar" body="predator"/>
	<character name="Unblooded" body="predator"/>
	<character name="Young Blooded" body="predator"/>
	<character name="Blooded" body="predator"/>
	<character name="Predalien" body="predator"/>
	<character name="Hunter" body="predator"/>
	<character name="Tracker" body="predator"/>
	<character name="Ceremonial" body="predator"/>	
	<character name="Mortal fighter" body="predator"/>
	<character name="Neo-predator" body="predator"/>
  </team>
    <color name="teamcolor" r="246" g="15" b="44" a="55" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/gnu/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Gnu</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Connochaetes Taurinus" body="gnu" />
    <character name="Connochaetes gnu" body="gnu" />
    <character name="Not UNIX" body="gnu" />
    <character name="Linux" body="gnu" />
    <character name="Hurd" body="gnu" />
    <character name="Emacs" body="gnu" />
    <character name="Compiler Collection" body="gnu" />
    <character name="Arch" body="gnu" />
    <character name="Debugger" body="gnu" />
    <character name="Savannah" body="gnu" />
  </team>
    <color name="teamcolor" r="111" g="85" b="50" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/suse/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>SuSE</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
	<character name="Geeko" body="suse"/>
	<character name="opensuse" body="suse"/>
	<character name="suse_LE" body="suse"/>
	<character name="ZYpp" body="suse"/>
	<character name="Microsuse" body="suse"/>
	<character name="Minisuse" body="suse"/>	
	<character name="SUPER" body="suse"/>
	<character name="Jacklab" body="suse"/>
	<character name="YaST" body="suse"/>
	<character name="Rhampholeon GÃ¼nther" body="suse"/>
	<character name="Chamaeleonidae" body="suse"/>
	<character name="Bradypodion Fitzinger" body="suse"/>
	<character name="Brookesia Gray" body="suse"/>
	<character name="Calumma Gray" body="suse"/>	
	<character name="Chamaeleo Laurenti" body="suse"/>
	<character name="Furcifer Fitzinger" body="suse"/>
  </team>
    <color name="teamcolor" r="71" g="120" b="25" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/hexley/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Hexley</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="Hexley" body="hexley" />
    <character name="DarwinOS" body="hexley" />
    <character name="Ornithorhynchus anatinus" body="hexley" />
    <character name="Thomas Henry" body="hexley" />
    <character name="Charles" body="hexley" />
    <character name="XNU" body="hexley" />
    <character name="Jon Hooper" body="hexley" />
    <character name="Rhapsody" body="hexley" />
	<character name="iPhone OS" body="hexley" />
    <character name="PureDarwin" body="hexley" />
	<character name="Apple TV" body="hexley" />
  </team>
    <color name="teamcolor" r="134" g="57" b="30" a="255" />
</resources>

=== Hipnosis183/OpenSourceGames/WarMUX/warmux/data/team/pidgin/team.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE resources SYSTEM "../team.dtd" []>
<resources>
  <name>Pidgin</name>
  <surface name="flag" file="flag.png" />
  <surface name="death_flag" file="dead.png" />
  <surface name="big_flag" file="flag64.png" />
  <team>
    <character name="AIM" body="pidgin"/>
    <character name="Bonjour" body="pidgin"/>
    <character name="Gadu-Gadu" body="pidgin"/>
    <character name="Google Talk" body="pidgin"/>
    <character name="Groupwise" body="pidgin"/>
    <character name="ICQ" body="pidgin"/>
    <character name="IRC" body="pidgin"/>
    <character name="MSN" body="pidgin"/>
    <character name="MySpaceIM" body="pidgin"/>
    <character name="QQ" body="pidgin"/>
    <character name="SILC" body="pidgin"/>
    <character name="SIMPLE" body="pidgin"/>
    <character name="Sametime" body="pidgin"/>
    <character name="XMPP" body="pidgin"/>
    <character name="Yahoo!" body="pidgin"/>
    <character name="Zephyr" body="pidgin"/>
  </team>
    <color name="teamcolor" r="131" g="80" b="142" a="255" />
</resources>
